---
title: "My website"
output: html_document
---

```{r, cache = TRUE}
escapement <- read.csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/knb.92020.1",
                       stringsAsFactors = FALSE)

# or if you downloaded it
# read.csv("ADFG_firstAttempt_reformatted.csv") # <- whatever you named the file
```

```{r}
library(tidyr)
library(dplyr)
library(leaflet)
library(ggplot2)
library(DT)
```

```{r}
# median annual esc. by species
median_esc <- escapement %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  group_by(Species, Location, Year) %>% 
  summarise(escapement = sum(DailyCount, na.rm = TRUE)) %>% 
  group_by(Species) %>% 
  summarise(median_escapement = median(escapement))
```

```{r}
ggplot(median_esc, aes(Species, median_escapement)) +
  geom_col() +
  coord_flip()
```

```{r}
datatable(median_esc)
```

```{r}
locations <- escapement %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()

leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(~ - abs(Longitude), ~ Latitude, popup = ~ Location)
```
